### PR TITLE
Add more options to columns, dont send disabled fields, better checkbox functionality, cleanup select dropdowns

### PR DESCRIPTION
**Pull request by thetechnician94**
Hi,

I've been using a modified version of the AltEditor for a while now and decided to contribute my changes to the larger community. 
I think I made all the changes I needed to for the Readme and the Changelog, I apologize if I missed anything. 

I also added js code to the minified version

Thanks!

### CODE REVIEW

**Comment by luca-vercelli** [comment]
Looks good to me.
Everything but the "value" property. I understand that, when I create a new record, this value will be used as default value. What happens if I modify a record?

**Comment by thetechnician94** [comment]
The modified value is used appropriately in that case. The "value" property only affects the "Add" dialog, which is accomplished using the existing code - I didn't need to add anything there.

**Comment by thetechnician94** [comment]
I did just realize that in the Readme.md I said that the "step" attribute takes an integer. That's not true. It takes a float (0.01 is a valid step). I don't think I can change that without doing a new pull.

**Comment by luca-vercelli** [comment]
Thank you.

**Pull request merged**
