### PR TITLE
checkbox and date type

### PR DESCRIPTION
**Pull request by mjbernot**
added checkbox and date type,
added css to textarea to match all other fields,

columnDefs:
added style allows users to pass in css for custom styled input types.
added dateFormat allows users to pass in a string ex.("YYYY-MM-DD") when using input date type uses momentjs to format the date
added optionsSortByLabel(true/false) allows select to be sorted by label field

Please let me know if you need more information about these changes, or if you have any suggestions.
Thanks

### CODE REVIEW

**Comment by luca-vercelli** [comment]
Great job! I will see it ASAP. Is the dateFormat parameter compatible with datetimepicker?

**Comment by luca-vercelli** [comment]
I do not agree with the "style=..." attribute of text areas. It should not be so specific. In the "input" fields there is nothing as such.

**Comment by luca-vercelli** [comment]
Can you please try with `class="form-control"` instead of `style="..."` ?

**Comment by mjbernot** [comment]
issue

Hi Luca, The class has a width and height defined that breaks the row and column.
I removed the css and added the style parameter.

**Comment by luca-vercelli** [comment]
Merged. Thank you.
Please notice that I have added the "form-control" class to text areas. It should really be the correct solution (see https://luca-vercelli.github.io/DataTable-AltEditor/example/01_in_memory_arrays/example1.html). I think that you have some more css stuff that "breaks the row and column".

**Comment by luca-vercelli** [comment]
closes issue #112

**Pull request merged**
